Dev refactor
bbquite/go-pass-keeper pull request #2
Opened 2024-12-04 13:40 UTC by bbquite

2024-12-16 17:48 UTC, bulbetski requested changes
В целом хорошо, в основном замечания по дублированию и немного по код стайлу

2024-12-16 17:48 UTC, bulbetski commented on internal/app/server/server.go
> +func NewGRPCServer(cfg *config.ServerConfig, logger *zap.SugaredLogger) (*gRPCServer, error) {
Все фатальные ошибки лучше выности в main, чтобы наверняка корректно контролировать всеми ресурсами программы.

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/cli.go
> +var ErrorCLIGracefullyStop = errors.New("cli gracefully stop")
Не используется

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/cli.go
> +func (cli *ClientCLI) Run() {
CLI должен предоставлять пользователю способ завершить выполнение программы. Рекомендуется добавить команду EXIT (или аналогичную), которая завершает выполнение

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/auth.go
> +func (cm *CommandManager) authCommand(params CommandParams) error {
Логика работы с параметрами, вызова методов authService и сохранения токена повторяется в обоих методах. Это можно вынести в отдельные функции

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/auth.go
> +func (cm *CommandManager) authCommand(params CommandParams) error {
Что-нибудь в духе:
```
func (cm *CommandManager) handleAuthAction(
    params CommandParams,
    action func(context.Context, map[string]*ValidatedParam) error,
) error
{

}
```

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/auth.go
> +	err = cm.saveFile("./auth.json", jsOut)
путь можно вынести в константу

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/comand.go
> +package command
Много дублирования кода. Команды имеют одинаковую структуру и их можно попробовать объединить или обернуть во что-нибудь

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/comand.go
> +package command
Пример:
```
func (cm *CommandManager) executeWithParams(
    params CommandParams,
    action func(params CommandParams) error,
) error {
    validatedParams := cm.validateParams(params)
    return action(validatedParams)
}
```
Таким образом authCommand может выглядеть так:
```
Execute: func() error {
    params := CommandParams{
        "username": {validateFunc: validator.StringValidation},
        "password": {validateFunc: validator.StringValidation},
    }
    return cm.executeWithParams(params, cm.authCommand)
}
```

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/comand.go
> +package command
Чтобы уменьшить объем кода в initCommandsThree и сделать его более читаемым, параметры для каждой команды можно вынести в константы.
Пример:
```
var AuthParams = CommandParams{
    "username": {validateFunc: validator.StringValidation},
    "password": {validateFunc: validator.StringValidation},
}

var BinaryParams = CommandParams{
    "id":       {validateFunc: validator.IntValidation},
    "filepath": {validateFunc: validator.FilePathValidation},
}
```
```
"AUTH": {
    Desc: "Authorization in the system by login and password",
    Execute: func() error {
        return cm.executeWithParams(AuthParams, cm.authCommand)
    },
},
"BINARY": {
    Desc: "Updating binary data",
    Execute: func() error {
        return cm.executeWithParams(BinaryParams, cm.updateCommand)
    },
},
```

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/comand.go
> +		},
Команда ничего не делает. Можно добавить список всех команд
```
for name, cmd := range cm.CommandRoot {
            fmt.Printf(" - %s: %s\n", name, cmd.Desc)
        }
        ```

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/comand.go
> +func (cm *CommandManager) initCommandsThree() {
Можно разбить этот метод на несколько вспомогательных методов, чтобы каждый отвечал за отдельную команду или группу команд

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/comand.go
> +func (c *Command) GetSubCommandsNames() string {
Можно упростить, использовав strings.Join

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/data.go
> +package command
Много кода повторяется в createCommand, updateCommand и других методах:
1. Проверка токена.
2. Обработка данных по типам (models.DataTypePAIR, models.DataTypeTEXT, и т.д.).
3. Валидация параметров.

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/data.go
> +package command
Можно сделать методы prepareData, где будет switch dataType. Метод ensureAuthorized, где будет проверка токена и т.д.

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/command/data.go
> +		}
Можно подумать, как вынести в отдельный метод

2024-12-16 17:48 UTC, bulbetski commented on internal/cli/validator/validator.go
> +package validator
Можно избавиться от дублирования:
```
func validate(param string, rules ...validation.Rule) error {
	err := validation.Validate(param, rules...)
	if err != nil {
		return fmt.Errorf("validation error: %w", err)
	}
	return nil
}
```

2024-12-16 17:48 UTC, bulbetski commented on internal/config/client.go
> +	jsonConfig, _ := json.Marshal(c)
Не обрабатываем ошибку

2024-12-16 17:48 UTC, bulbetski commented on internal/handlers/auth.go
> +func (h *GRPCHandler) RegisterUser(ctx context.Context, in *pb.RegisterUserRequest) (*pb.RegisterUserResponse, error) {
Можно не инициализировать ответ в самом начале, а в случае ошибки возвращать nil, status.Error()

2024-12-16 17:48 UTC, bulbetski commented on internal/handlers/data.go
> +	}
Преобразование данных из pb.DataItem в models.DataStoreFormat повторяется во многих методах. Можно сделать какой-нибудь хелпер типа convertPBDataItemToModel

2024-12-16 17:48 UTC, bulbetski commented on internal/handlers/data.go
> +	}
Ну и соотственно сделать хелпер, который делает обратную конвертацию convertModelToPBDataItem

2024-12-16 17:48 UTC, bulbetski commented on internal/service/client/auth.go
> +	service.store.SetToken(&token)
не обрабатываем ошибку

2024-12-16 17:48 UTC, bulbetski commented on internal/service/client/auth.go
> +	service.store.SetToken(&token)
Не обрабатываем ошибку

2024-12-16 17:48 UTC, bulbetski commented on internal/service/client/data.go
> +	}
Проверка на наличие токена (service.store.GetToken() == "") повторяется в каждом методе. Стоит вынести эту логику в отдельную функцию. И возвращать в конце, например

return metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+token), nil

2024-12-16 17:48 UTC, bulbetski commented on internal/service/client/data.go
> +	})
Конвертации из model в pb и наоборот вынести в методы конвертаторы

2024-12-16 17:48 UTC, bulbetski commented on internal/service/server/auth.go
> +package server
Логика генерации токена повторяется, стоит вынести в отдельный метод

2024-12-16 17:48 UTC, bulbetski commented on internal/service/server/data.go
> +	accountID := ctx.Value(utils.UserIDKey).(uint32)
Извлечение accountID из контекста часто повторяется. Надо вынести в хелпер и внутри проверять ошибку приведения типа, потому что неправильный тип может привести к панике

2024-12-16 17:48 UTC, bulbetski commented on internal/storage/postgres/auth.go
> +		LIMIT 1
Если таблица имеет уникальные ограничения (например, UNIQUE или PRIMARY KEY на поле username), то LIMIT 1 не требуется, так как SQL-запрос гарантирует возврат не более одной строки

2024-12-16 17:48 UTC, bulbetski commented on internal/storage/postgres/data.go
> +		RETURNING id, data_type, data_info, meta, uploaded_at
Достаточно вернуть id и uploaded_at, остальное у нас уже имеется

2024-12-16 17:48 UTC, bulbetski commented on internal/storage/postgres/data.go
> +
В методе GetDataList rows открывается с помощью QueryContext. Однако, нет гарантии, что соединение будет закрыто при возникновении ошибки. Всегда надо использовать defer rows.Close() для закрытия соединений

2024-12-16 17:48 UTC, bulbetski commented on internal/storage/postgres/data.go
> +func (storage *DBStorage) UpdateData(ctx context.Context, accountID uint32, data *models.DataStoreFormat) error {
Методы UpdateData и DeleteData не проверяют, была ли затронута хотя бы одна строка. Это может быть полезно, чтобы убедиться, что операция выполнена успешно.
Можно проверять
```
rowsAffected, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if rowsAffected == 0 {
		return fmt.Errorf("no rows updated for data ID %d", data.ID)
	}

```

2024-12-16 17:48 UTC, bulbetski commented on internal/storage/postgres/data.go
> +		LIMIT 1
Если id это primary key, то тут limit не нуже

2024-12-25 08:27 UTC, bbquite commented on internal/app/server/server.go
> +func NewGRPCServer(cfg *config.ServerConfig, logger *zap.SugaredLogger) (*gRPCServer, error) {
done

2024-12-25 08:32 UTC, bbquite commented on internal/cli/command/auth.go
> +	err = cm.saveFile("./auth.json", jsOut)
done

2024-12-26 07:15 UTC, bbquite commented on internal/cli/command/comand.go
> +func (cm *CommandManager) initCommandsThree() {
done

2024-12-26 08:53 UTC, bbquite commented on internal/cli/command/comand.go
> +package command
done

2024-12-27 18:11 UTC, bbquite commented on internal/handlers/auth.go
> +func (h *GRPCHandler) RegisterUser(ctx context.Context, in *pb.RegisterUserRequest) (*pb.RegisterUserResponse, error) {
done

2024-12-27 18:12 UTC, bbquite commented on internal/service/client/auth.go
> +	service.store.SetToken(&token)
done

2024-12-27 18:12 UTC, bbquite commented on internal/service/client/auth.go
> +	service.store.SetToken(&token)
done

2024-12-27 18:16 UTC, bbquite commented on internal/storage/postgres/data.go
> +		LIMIT 1
done

2024-12-27 18:18 UTC, bbquite commented on internal/storage/postgres/data.go
> +func (storage *DBStorage) UpdateData(ctx context.Context, accountID uint32, data *models.DataStoreFormat) error {
done

2024-12-27 18:18 UTC, bbquite commented on internal/storage/postgres/data.go
> +
done

2024-12-27 18:21 UTC, bbquite commented on internal/storage/postgres/data.go
> +		RETURNING id, data_type, data_info, meta, uploaded_at
done

2024-12-27 18:28 UTC, bbquite commented on internal/service/server/data.go
> +	accountID := ctx.Value(utils.UserIDKey).(uint32)
done

2024-12-27 18:35 UTC, bbquite commented on internal/cli/validator/validator.go
> +package validator
+-

2024-12-27 18:35 UTC, bbquite commented on internal/config/client.go
> +	jsonConfig, _ := json.Marshal(c)
+-

2024-12-27 18:36 UTC, bbquite commented on internal/handlers/data.go
> +	}
дубль

2025-01-05 12:49 UTC, bbquite commented on internal/cli/command/auth.go
> +func (cm *CommandManager) authCommand(params CommandParams) error {
done

2025-01-05 13:27 UTC, bbquite commented on internal/cli/command/data.go
> +		}
done

2025-01-05 16:28 UTC, bbquite commented on internal/cli/command/data.go
> +package command
done

2025-01-06 16:54 UTC, bbquite commented on internal/cli/cli.go
> +var ErrorCLIGracefullyStop = errors.New("cli gracefully stop")
done

2025-01-06 16:54 UTC, bbquite commented on internal/cli/cli.go
> +func (cli *ClientCLI) Run() {
done

2025-01-06 17:33 UTC, bbquite commented on internal/service/client/data.go
> +	}
done

2025-01-06 17:35 UTC, bbquite commented on internal/service/client/data.go
> +	})
done

2025-01-21 00:08 UTC, bulbetski approved these changes
Норм исправил

p.s. просьба на будущее, не резолвь плиз комменты. Это как бы ревьюера задача и плюс ко всему доверия особо нет (без негатива, так и на работе) к тому, кто делает исправления. Кароч неудобно открывать каждый раз коммент и смотреть, исправил человек что-то или нет

2025-01-22 10:41 UTC, merged